### ISSUE TITLE
[BUG] MemoryError when creating an instance of IntegerPolynomial for integers with a large number of bits

### ISSUE THREAD

**Issue by BusyBeaver-42** [bqth29/simulated-bifurcation-algorithm#13]
# Description
Creating an instance of `IntegerPolynomial` over integers with a large number of bits raises a `MemoryError`.

The `IntegerPolynomial.__init__` creates a list of all accepted values which has size `2**number_of_bits`.

# Code example
```python
import torch
import simulated_bifurcation as sb

sb.build_model(matrix, input_type="int42")
```

# Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\agero\PycharmProjects\simulated-bifurcation-algorithm\.test_env\.pypi_env_no_gpu\lib\site-packages\simulated_bifurcation\simulated_bifurcation.py", line 823, in build_model
    return IntegerPolynomial(
  File "C:\Users\agero\PycharmProjects\simulated-bifurcation-algorithm\.test_env\.pypi_env_no_gpu\lib\site-packages\simulated_bifurcation\polynomial\integer_polynomial.py", line 60, in __init__
    matrix, vector, constant, [*range(2**number_of_bits)], dtype, device
MemoryError
```

**Comment by BusyBeaver-42** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change accepted values verification](https://trello.com/c/Yow1AEzZ/45-change-accepted-values-verification)

**Comment by bqth29** [comment]
This problem stems from the fact that the list of possible values has to be generated before the polynomial is evaluated, to ensure that the input values actually belong to the polynomial's definition domain.

From version 1.3.0 onwards (the first PR of which is #37), polynomials will no longer have a default definition domain (the domain will only need to be specified when casting the polynomial in an Ising model or when converting SB-optimized spins back to the origin domain). As a result, there will be no need to check the values when evaluating the polynomial, which solves this problem.
