### ISSUE TITLE
Error when running on CUDA

### ISSUE THREAD

**Issue by MahmoodSpewAfsh** [bqth29/simulated-bifurcation-algorithm#73]
Hi Guys 
When I tried to run the SB with cuda I get the erro below:
[/usr/local/lib/python3.10/dist-packages/simulated_bifurcation/optimizer/stop_window.py](https://localhost:8080/#) in __compare_energies(self, sampled_spins)
    111             sampled_spins.t(), sampled_spins.t(), torch.unsqueeze(self.ising_tensor, 0)
    112         ).reshape(self.n_agents)
--> 113         torch.eq(
    114             energies,
    115             self.energies,

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by Ali-Xoerex** [comment]
#74 fixes this issue

**Comment by MahmoodSpewAfsh** [comment]
> #74 fixes this issue

Thanks it worked
